# Generated by Django 3.0.5 on 2020-08-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_post_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='text',
            new_name='comments',
        ),
    ]
